import { useEffect, useState } from "react";
import { Star, Quote, Send, Radio, CheckCircle2 } from "lucide-react";
import PulseDivider from "../../../components/PulseDivider";
import { api } from "../../lib/api";

export default function Testimonials() {
  const [items, setItems] = useState([]);
  const [form, setForm] = useState({ name: "", procedure: "", rating: 5, comment: "" });
  const [status, setStatus] = useState("");
  const load = async () => { try { setItems(await api("/testimonials")); } catch { setStatus("The live review service is offline. Start the server to enable live comments."); } };
  useEffect(() => { load(); const timer = setInterval(load, 5000); return () => clearInterval(timer); }, []);
  const submit = async e => { e.preventDefault(); setStatus("Sending..."); try { await api("/testimonials", { method: "POST", body: JSON.stringify(form) }); setForm({ name: "", procedure: "", rating: 5, comment: "" }); setStatus("Your testimonial is now live on this page."); load(); } catch (err) { setStatus(err.message); } };
  return <div className="mx-auto max-w-7xl px-4 pt-32 pb-20 sm:px-6 lg:px-8 lg:py-24">
    <div className="mx-auto max-w-2xl text-center"><PulseDivider label="Testimonials"/><h1 className="mt-5 text-3xl font-semibold sm:text-4xl">Real patient feedback</h1><p className="mt-4 leading-relaxed text-slate-600 dark:text-slate-300">New comments submitted through this page are stored by the ZarinCare API and automatically appear for visitors.</p><div className="mt-5 inline-flex items-center gap-2 rounded-full border border-purple-200 bg-purple-50 px-4 py-2 text-xs font-medium text-purple-700 dark:border-purple-900 dark:bg-purple-950/30 dark:text-purple-300"><Radio size={14} className="animate-pulse"/> Live updates every 5 seconds</div></div>
    <div className="mt-14 grid gap-8 lg:grid-cols-[1.4fr_.8fr]">
      <div className="grid gap-6 md:grid-cols-2">{items.length ? items.map(t=><article key={t.id} className="group rounded-2xl border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:border-purple-300 hover:shadow-xl dark:border-slate-800 dark:bg-slate-900/70"><Quote className="text-purple-500" size={22}/><p className="mt-4 leading-7 text-slate-600 dark:text-slate-300">“{t.comment}”</p><div className="mt-6 border-t border-slate-200 pt-4 dark:border-slate-800"><div className="flex justify-between gap-3"><div><p className="font-semibold">{t.name}</p><p className="text-xs text-slate-400">{t.procedure}</p></div><div className="flex">{Array.from({length:t.rating}).map((_,i)=><Star key={i} size={14} className="fill-purple-500 text-purple-500"/>)}</div></div><p className="mt-2 text-[10px] uppercase tracking-widest text-slate-400">{new Date(t.createdAt).toLocaleString()}</p></div></article>) : <div className="md:col-span-2 rounded-2xl border border-dashed border-slate-300 p-12 text-center dark:border-slate-700"><p className="font-semibold">No patient testimonials have been submitted yet.</p><p className="mt-2 text-sm text-slate-500">Be the first to share your experience.</p></div>}</div>
      <form onSubmit={submit} className="h-fit rounded-3xl border border-slate-200 bg-white p-7 shadow-sm dark:border-slate-800 dark:bg-slate-900/70"><h2 className="text-xl font-semibold">Share your experience</h2><p className="mt-2 text-sm text-slate-500 dark:text-slate-300">Only publish a review you are comfortable sharing publicly.</p><div className="mt-6 space-y-4"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your name" className="w-full rounded-xl border border-slate-300 bg-transparent px-4 py-3 outline-none focus:border-purple-500 dark:border-slate-700"/><input value={form.procedure} onChange={e=>setForm({...form,procedure:e.target.value})} placeholder="Procedure / care type (optional)" className="w-full rounded-xl border border-slate-300 bg-transparent px-4 py-3 outline-none focus:border-purple-500 dark:border-slate-700"/><div><label className="text-xs font-medium text-slate-500">Rating</label><select value={form.rating} onChange={e=>setForm({...form,rating:Number(e.target.value)})} className="mt-1 w-full rounded-xl border border-slate-300 bg-transparent px-4 py-3 dark:border-slate-700"><option value="5">★★★★★ — Excellent</option><option value="4">★★★★ — Very good</option><option value="3">★★★ — Good</option><option value="2">★★ — Fair</option><option value="1">★ — Needs improvement</option></select></div><textarea required rows="6" value={form.comment} onChange={e=>setForm({...form,comment:e.target.value})} placeholder="Write your comment..." className="w-full resize-none rounded-xl border border-slate-300 bg-transparent px-4 py-3 outline-none focus:border-purple-500 dark:border-slate-700"/><button className="flex w-full items-center justify-center gap-2 rounded-full bg-purple-600 px-6 py-3 font-semibold text-white hover:bg-purple-700"><Send size={16}/> Publish testimonial</button>{status && <p className="flex items-center gap-2 text-xs text-slate-500"><CheckCircle2 size={14} className="text-purple-500"/>{status}</p>}</div></form>
    </div>
  </div>;
}
